### ISSUE TITLE
GNU Assembler does NOT support relaxation

### ISSUE THREAD

**Issue by NandniJamnadas** [pietraferreira/corev-binutils-gdb#8]
If the immediate offset is **less than 4**, the following instructions relaxes to incorrect encodings: 
- c.lbu relaxes to cm.lbu
- c.lhu relaxes to cm.lhu
- c.lh relaxes to cm.lh
- c.sb relaxes to cm.sb
- c.sh relaxes to cm.sh

"If uimm < 4 the encoding is designated for custom use, as the functionality overlaps with
c.lbu: Load unsigned byte, 16-bit encoding."

It is illegal to have the cm.* instructions to execute if the immediate offset is less than 4 as this is designed for custom use.

**Comment by pietraferreira** [comment]
Awaiting tests.
